# -*- coding: utf-8 -*-
"""Eliza-like - Travel Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJYAaFGQcPcRs5MHfxvnLj6H_1mJPH3A
"""

# Description: This program is an Travel assistant similar to Eliza

import re
import random

# list of pre-defined responses
response = {
    "hello": ["Hello! Where are you planning to travel?"],
    "how are you": ["I'm just a travel assistant, but I'm here to help you plan your next trip!"],
    "i want to visit (.*)": ["That sounds amazing! Have you been to {} before?", "What interests you about {}?"],
    "what can I do in (.*)": ["There are plenty of things to do in {}! Do you prefer adventure, relaxation, or sightseeing?", "What kind of activities are you looking for in {}?"],
    "how is the weather in (.*)": ["The weather in {} can vary! What time of year are you planning to go?", "Would you like tips on what to pack for {}?"],
    "what should I eat in (.*)": ["{} has amazing local food! Do you prefer street food or fine dining?", "Would you like recommendations for must-try dishes in {}?"],
    "how do I get to (.*)": ["There are several ways to travel to {}. Are you looking for flights, trains, or road trip options?", "Would you like budget-friendly travel tips for {}?"],
    "(.*) hotel (.*)": ["Are you looking for luxury hotels or budget-friendly stays?", "What type of accommodation do you prefer?"],
    "(.*) budget (.*)": ["Are you looking for budget travel tips or ways to save money on your trip?", "Would you like recommendations for affordable places to stay and eat?"],
    "(.*) landmarks in (.*)": ["{1} has some famous landmarks! Are you interested in historical sites or natural attractions?", "Would you like recommendations for must-see landmarks in {1}?"],
    "(.*) best time to visit (.*)": ["The best time to visit {1} depends on the weather and events. Are you looking for peak season or off-season travel?", "Do you prefer visiting {1} during a festival or when it’s less crowded?"],
    "(.*) activities in (.*)": ["There are so many activities to do in {1}! Are you interested in outdoor adventures or cultural experiences?", "Would you like suggestions for unique activities in {1}?"],
    "(.*) transportation in (.*)": ["Getting around {1} is easy! Are you looking for public transport, rental cars, or walking tours?", "Would you like tips on the best ways to travel within {1}?"],
    "(.*) travel tips for (.*)": ["{1} is a great destination! Are you looking for safety tips, cultural etiquette, or general travel advice?", "Would you like packing tips for {1}?"],
    "(.*) nightlife in (.*)": ["The nightlife in {1} is vibrant! Do you prefer clubs, bars, or cultural performances?", "Would you like recommendations for the best places to enjoy the nightlife in {1}?"],
    "yes": ["Perfect! What’s next?", "Glad to hear that!", "That’s what I like to hear!", "Are you planning to go again?"],
    "no": ["lets plan the best vacations for you", "That’s totally fine! Let me know what you're looking for.", "That’s alright! Let’s figure out what works best for you.", "All good! Travel plans should be flexible—let’s find what’s right for you.", "That’s okay! Let’s look at some other great options."],
    ".*": ["That sounds great!", "Interesting! Tell me more.", "Oh, that’s exciting!", "Got it!", "let me see what can I do for you", "noted", "I hear you"],

}

# function to match user input
def match_response(user_input):
  for pattern, response_list in response.items():
    matches = re.match(pattern, user_input.lower())
    if matches:
      chosen_response = random.choice(response_list)
      return chosen_response.format(*matches.groups())
  # if there is no pattern match
  return "I'm sorry I dont understand what you're saying."

# main
print("Welcome to the Travel Assistant! How can I help you plan your next trip?")
while True:
  user_input = input("You: ")
  if user_input == "bye":
    print("Travel Assistant: Goodbye! Have a great trip!")
    break
  else:
    print("Travel Assistant: ", match_response(user_input))